### ISSUE TITLE
Grass not Showing in Unity

### ISSUE THREAD

**Issue by jamil2001** [theboywhomakesgames/unity-optimized-grass#1]
Well sorry, but I dont know why I cant see any grass on play.

**Comment by theboywhomakesgames** [comment]
I hear you!
Try to switch from vulkan to opengl (there's a box in unity project settings you can change the priority of different frameworks used)

if that doesn't work, just inform me right here so we can fix it

**Comment by jamil2001** [comment]
![Screenshot (120)](https://user-images.githubusercontent.com/66199668/149205031-1a5e7452-b6dc-40b5-b5d0-660d2d7ba4ed.png)
I came here, but cant find the OpenGL or Vulkan swa
![Screenshot (121)](https://user-images.githubusercontent.com/66199668/149205134-8d14ec2e-19d9-4da8-a4f2-9404d3b7869e.png)
Should Render texture, last render texture and grass texture stay empty?

**Comment by willlogs** [comment]
_Should Render texture, last render texture and grass texture stay empty?_
Yes those textures are assigned on the fly by the code.

![image](https://user-images.githubusercontent.com/25264657/149292244-8c0c61de-c777-4aa0-bc35-7d75e5921343.png)
for android and:
![image](https://user-images.githubusercontent.com/25264657/149292904-10b0cec2-ce47-43ba-a952-a2c9da3f167c.png)
if your platform is PC/MAC, just uncheck the "auto graphics api" and set it to openGL.

If the grass is not showing without the mesh being painted pink it only goes back to one thing: You are using Vulkan. Don't use vulkan. Vulkan sucks :D

Please inform me if it works. Best of luck

**Comment by theboywhomakesgames** [comment]
![image](https://user-images.githubusercontent.com/25264657/149292747-43c11862-ca73-4592-8ce3-d923e1609dc2.png)
Here's the one for PC
Uncheck that "auto api" thing for each platform and set it all to OpenGL 3.5+

**Comment by jamil2001** [comment]
Sorry again, but I am getting this warning 
1) GarbageCollector disposing of ComputeBuffer allocated in F:\unity project\Phantom\Assets\unity-optimized-grass-main\Assets\_\Garden\Scripts\GrassPatchActivator.cs at line 60. Please use ComputeBuffer.Release() or .Dispose() to manually release the buffer.
UnityEngine.ComputeBuffer:Finalize () 
and also 
2) InkCanvas has been destroyed.
UnityEngine.Debug:Log (object)
Es.InkPainter.InkCanvas:OnDestroy () (at Assets/unity-optimized-grass-main/Assets/Packages/InkPainter/Script/Core/InkCanvas.cs:288)

**Comment by willlogs** [comment]
Sorry to answer a bit late.
Could you please open up a new issue for this one since it's different from the initial issue. And if you figured it out please inform me.

I'll have to check the project for this bug you are experiencing and I'll get back to you in a week.
It probably needs a .Dispose() at the end of the update function. But I'll have to double check which takes some time.
