### ISSUE TITLE
Not working on IOS

### ISSUE THREAD

**Issue by YakupFistikcioglu** [theboywhomakesgames/unity-optimized-grass#2]
Hello there,

First of all, thank you for the package.
My pc is macbook m1 pro and i am using intel version 2021.2.12f1 in unit. When I opened the demo scene, I saw that all the materials were purple. Shaders do not have any shaders other than PT / HideGrass. There is only PT/ HideGrass. And render Texture, LastRender Texture, Grass Texture none in Grass Patch Activator Script On Inspector. what should i do for this?

Can you please help?

**Comment by willlogs** [comment]
Hi there!

Have you checked out the other issue about OpenGL setup of the project? Doesn't that fix things?

**Comment by YakupFistikcioglu** [comment]
as a result of my research, iOS does not support opengl :( 

so it doesn't work.

**Comment by theboywhomakesgames** [comment]
This shader works on any device that supports tesselation shaders

**Comment by willlogs** [comment]
This shader works on any device that supports tesselation shaders && OpenGL
