### ISSUE TITLE
Percentage of mowed grass

### ISSUE THREAD

**Issue by KutlayMD** [theboywhomakesgames/unity-optimized-grass#5]
Hi,

Is there a way to get mowed grasses percentage? and can we paint the grass?

Your work is perfect, thank you :)

**Comment by willlogs** [comment]
Hi

Yes! There is!
If you go to my profile, stars and then there's a list there called "My
Hyper Casuals". In there you'll find a game called Beelawn that uses this
same asset and also has a percentage thingy.

Hope it helps.
Best
