### ISSUE TITLE
Everything is PINK!

### ISSUE THREAD

**Issue by scg-nikhil** [theboywhomakesgames/unity-optimized-grass#7]
Hey , thanks for this awesome interactive grass,
I opened the project in Unity 2021.3.3f1 , but I couldn't see any grass, everything is pink, 
Any help will be greatly appreciated!

Thanks in advance :
<img width="714" alt="Screenshot 2022-06-29 at 12 18 32 PM" src="https://user-images.githubusercontent.com/106652468/176370246-6572f2f1-78b2-4ad7-b5be-c082985bb572.png">
)

**Comment by willlogs** [comment]
Hi,

Make sure you're not in urp and check out the other issues. I'm sure there
is another issue about the same problem.

Best of luck

**Comment by scg-nikhil** [comment]
Hey, thanks , I have been checking in 
"issues" section, and I found the solution in "Closed" section.
Thanks!

**Comment by Umair130815** [comment]
> Hey, thanks , I have been checking in "issues" section, and I found the solution in "Closed" section. Thanks!

Hey! I am facing the same problem. Can you tell me which issue gave you the solution?
